# General parameters
digits = 128    # number of digits
gaver_order = 8 # order of the Gaver sequence

ln_type = "Tidal" # LN type ('Loading' or 'Tidal')

min_degree = 2  # Minimum degree
max_degree = 2  # Maximum degree
degree_step = 1 # Step

time_scale = "ext"   # Time scale ('log' / 'lin' / 'ext')
time_points = 0      # Time points (minus one)
time_range = [-3, 2] # Time range (10^(m1:m2) kyrs)

# Load time history
load_function = "step" # Load function ('step' / 'ramp')
ramp_length = 1.0      # Ramp length (kyrs)

# Rheological model
num_layers = 10 # Number of layers

models = ["MODELS/Moon_Weber2011.dat"]

# Log file
log_file = "alma.log"

# Output files
ln_type_output = "Complex" # 'Real' or 'Complex' LNs
output_format = "ln_vs_t"  # Output file format (LNs vs t or LNs vs n)

output_files = ["h.dat", "l.dat", "k.dat"]
